In [6]:
import numpy as np

# Define grid dimensions
grid_size = 10

# Create a grid of zeros
grid = np.zeros((grid_size, grid_size), dtype=int)

# Calculate the center of the grid
center_x = grid_size // 2
center_y = grid_size // 2

# Define radius of the circle
radius = min(center_x, center_y) - 1  # Ensure the circle fits within the grid

# Add obstacles in a circular pattern
for x in range(grid_size):
    for y in range(grid_size):
        if (x - center_x)**2 + (y - center_y)**2 <= radius**2:
            grid[x, y] = 1

# Print the circular grid with obstacles
print(grid)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 0 0 0 0]]


In [5]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 81.4 MB/s eta 0:00:0000:0100:01


In [7]:
import numpy as np

# Define grid dimensions
grid_size = 10

# Create a grid of zeros
grid = np.zeros((grid_size, grid_size), dtype=int)

# Calculate the center of the grid
center_x = grid_size // 2
center_y = grid_size // 2

# Define radius of the circle
radius = min(center_x, center_y) - 1  # Ensure the circle fits within the grid

# Define the corners to add obstacles
corners = [(0, grid_size-1), (grid_size-1, grid_size-1), (grid_size-1, 0)]

# Add obstacles in a circular pattern in the defined corners
for corner in corners:
    corner_x, corner_y = corner
    for x in range(grid_size):
        for y in range(grid_size):
            if (x - corner_x)**2 + (y - corner_y)**2 <= radius**2:
                grid[x, y] = 1

# Print the grid with obstacles in the specified corners
print(grid)


[[0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 1 1]
 [1 1 1 1 0 0 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [8]:
def traverse_circular(grid, center, radius):
    x, y = center
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]  # Clockwise: right, down, left, up
    dx, dy = directions[0]  # Start moving right
    visited = set()

    for r in range(1, radius + 1):
        for _ in range(4):  # Move right, down, left, up
            for _ in range(r):
                x += dx
                y += dy
                if 0 <= x < len(grid) and 0 <= y < len(grid[0]):
                    visited.add((x, y))

            dx, dy = -dy, dx  # Rotate direction (clockwise)

    return visited

# Sample grid
grid = [
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
]

center = (len(grid) // 2, len(grid[0]) // 2)  # Center of the grid
radius = 2  # Radius of circular traversal

visited_coordinates = traverse_circular(grid, center, radius)
print("Visited Coordinates:")
for coord in visited_coordinates:
    print(coord)

Visited Coordinates:
(2, 4)
(1, 2)
(0, 4)
(0, 3)
(1, 4)
(2, 3)
(0, 2)
(2, 2)
(1, 3)


In [4]:
!pip install tk


Defaulting to user installation because normal site-packages is not writeable
