In [6]:
import numpy as np

# Define grid dimensions
grid_size = 10

# Create a grid of zeros
grid = np.zeros((grid_size, grid_size), dtype=int)

# Calculate the center of the grid
center_x = grid_size // 2
center_y = grid_size // 2

# Define radius of the circle
radius = min(center_x, center_y) - 1  # Ensure the circle fits within the grid

# Add obstacles in a circular pattern
for x in range(grid_size):
    for y in range(grid_size):
        if (x - center_x)**2 + (y - center_y)**2 <= radius**2:
            grid[x, y] = 1

# Print the circular grid with obstacles
print(grid)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 0 0 0 0]]


In [5]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 81.4 MB/s eta 0:00:0000:0100:01


In [7]:
import numpy as np

# Define grid dimensions
grid_size = 10

# Create a grid of zeros
grid = np.zeros((grid_size, grid_size), dtype=int)

# Calculate the center of the grid
center_x = grid_size // 2
center_y = grid_size // 2

# Define radius of the circle
radius = min(center_x, center_y) - 1  # Ensure the circle fits within the grid

# Define the corners to add obstacles
corners = [(0, grid_size-1), (grid_size-1, grid_size-1), (grid_size-1, 0)]

# Add obstacles in a circular pattern in the defined corners
for corner in corners:
    corner_x, corner_y = corner
    for x in range(grid_size):
        for y in range(grid_size):
            if (x - corner_x)**2 + (y - corner_y)**2 <= radius**2:
                grid[x, y] = 1

# Print the grid with obstacles in the specified corners
print(grid)


[[0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 1 1]
 [1 1 1 1 0 0 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
